name: simple_location_picker
description: A Simple Location Picker for Flutter using OpenStreetMap. Pick any location from openstreetmaps or use it to display a fixed location.
version: 0.0.4
homepage: https://github.com/hashirabdulbasheer/simple_location_picker

# This package is not publishable because it has git dependencies; it can only
# be used as a git dependency itself.
publish_to: none

environment:
  sdk: ^2.12.3
  flutter: ^2.0.6

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map
      ref: issues/829-nullsafety
  latlong2: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

dependency_overrides:
  flutter_image:
    git:
      url: https://github.com/Ascenio/flutter_image
      ref: a788edd8779e1dbb193d29b8732566422b6629f8

flutter:
